// @ts-check
// Sidebar is generated from the docs/ folder structure, ordered by each file's
// `sidebar_position` frontmatter and each folder's `_category_.json`.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
